Fix for newer satpy
Loading BANDNAMES angles and lat/lon in one go, sometimes
causes the program to fail.

KeyError: "No dataset matching 'DatasetID(name='sun_sensor_azimuth_difference_angle', wavelength=None, resolution=None, polarization=None, calibration=None, level=None, modifiers=None)' found"