Fix orbit_number attribute
In some situations when reading from C PPS count on orbit_number beeing an integer.

The error message is:
TypeError: an integer is required

In later versions of PPS, the problem might be fixed.

For python3 things usually work anyway.